# Operações de algebra linear usando python

In [ ]:
import numpy as np

In [ ]:
def forloop(x, w): 
    z = 0.
    for i in range(len(x)): 
        z += x[i] * w[i]
    return z

def listcomprehension(x, w):
    return sum(x_i*w_i for x_i, w_i in zip(x, w))

def vectorized(x, w): 
    return x_vec.dot(w_vec)

x, w = np.random.rand(100000), np.random.rand(100000)

In [3]:
%timeit -r 100 -n 10 forloop(x, w)

50.7 ms ± 1.05 ms per loop (mean ± std. dev. of 100 runs, 10 loops each)


In [ ]:
%timeit -r 100 -n 10 listcomprehension(x, w)

In [ ]:
%timeit -r 100 -n 10 listcomprehension(x, w)

In [ ]:
X = 2 * np.random.rand(100,1)
y = 4 +3 * X+np.random.randn(100,1)

In [ ]:
theta_best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [ ]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
#res=np.matmul(a, c)
res=a*c
res

In [23]:
a = np.random.rand(2, 2)
c = np.random.rand(2, 2)
a = np.ones([2,2])
c = np.ones([2,2])

c=[[3,3],[2,2]]
print(a)
print(c)
res0=np.dot(a, c)
res1=np.matmul(a, c)
res2=np.multiply(a, c)
res3=a*c
print(res0)
print(res1)
print(res2)
print(res3)

[[1. 1.]
 [1. 1.]]
[[3, 3], [2, 2]]
[[5. 5.]
 [5. 5.]]
[[5. 5.]
 [5. 5.]]
[[3. 3.]
 [2. 2.]]
[[3. 3.]
 [2. 2.]]


In [31]:
a = np.ones([3])
a = [1,10,20]
c = [0,1,2]
print(a)
print(c)
res0=np.dot(a, c)
res0


[1, 10, 20]
[0, 1, 2]


50

output = [1, 10, 20].[0, 1, 2]
       = 1*0 + 10*1 + 20*2
       = 50

In [34]:
#initialize arrays
A = np.array([[2, 1], [5, 4]])
B = np.array([[3, 4], [7, 8]])

#dot product
output = np.dot(A, B)
print(output)

[[13 16]
 [43 52]]
[[ 6  4]
 [35 32]]


output = [[2, 1], [5, 4]].[[3, 4], [7, 8]] 
       = [[2*3+1*7, 2*4+1*8], [5*3+4*7, 5*4+4*8]] 
       = [[13, 16], [43, 52]] 

In [ ]:
np.linalg.inv

Matriz Inversa

Anxn . A-1nxn = A-1nxn . Anxn = Inxn

In [35]:
#initialize arrays
A = np.array([[2, 1], [5, 4]])
B = np.array([[3, 4], [7, 8]])

#calculando inversa
output = np.linalg.inv(A)
print(output)
output = np.linalg.inv(B)
print(output)

[[ 1.33333333 -0.33333333]
 [-1.66666667  0.66666667]]
[[-2.    1.  ]
 [ 1.75 -0.75]]
