# Tensorflow
* Elementos Básicos da Linguagem

## Instalando tensorflow
* conda install tensorflow
* conda install tensorflow-gpu

In [6]:
import tensorflow as tf; 
print(tf.__version__)

2.2.0


## Modo eager executado por padrão no Tensorflow 2

In [ ]:
if(tf.executing_eagerly()):
    print('Eager execution is enabled (running operations immediately)\n')
    print(('Turn eager execution off by running: \n{0}\n{1}').format('' \
        'from tensorflow.python.framework.ops import disable_eager_execution', \
        'disable_eager_execution()'))
else:
    print('You are not running eager execution. TensorFlow version >= 2.0.0' \
          'has eager execution enabled by default.')
    print(('Turn on eager execution by running: \n\n{0}\n\nOr upgrade '\
           'your tensorflow version by running:\n\n{1}').format(
           'tf.compat.v1.enable_eager_execution()',
           '!pip install --upgrade tensorflow\n' \
           '!pip install --upgrade tensorflow-gpu'))

# Como desligar modo eager


In [ ]:
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

# Retornar ao modo eager (é necessário reiniciar o kernel)

In [ ]:
tf.compat.v1.enable_eager_execution()

# Versão 1 do tensorflow

* Executando grafo computacional

In [ ]:
# criar sessão
tf.compat.v1.Session(
    target='', graph=None, config=None
)

print(tf.__version__)

# construir o graph.
a = tf.constant(5.0)
b = tf.constant(2.3)
c = a * b

#  carregar o grafo na sessão
sess = tf.compat.v1.Session()

# Executar o grafo
print(sess.run(c))

# Exemplo de multiplicação de dois valores constante usando tensorflow

In [8]:
a = tf.constant(5)
b = tf.constant(3)
c = a * b
# mostra o objeto tensor
print(c)
# mostra apenas o valor
tf.print(c)



tf.Tensor(15, shape=(), dtype=int32)
15
15
<class 'numpy.int32'>
tf.Tensor(15, shape=(), dtype=int32)


# conversão numpy tensor <-> tensor numpy

In [ ]:
c = tf.constant(5)

#converte o tensor para numpy
numpyC = c.numpy()
print(numpyC)
print(type(numpyC))

#convert numpy para tensor
cc=tf.convert_to_tensor(numpyC)
print(cc)

# Verificar se há GPU disponível para uso
* list_physical_devices()

In [11]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]


In [ ]:
print(tf.config.list_physical_devices('GPU'))

print(('Is your GPU available for use?\n{0}').format(
    'Yes, your GPU is available: True' if tf.test.is_gpu_available() == True else 'No, your GPU is NOT available: False'
))

print(('\nYour devices that are available:\n{0}').format(
    [device.name for device in tf.config.experimental.list_physical_devices()]
))

# Escolhendo o device que vai executar o código TF GPU e CPU para comparar tempo
* tf.device

In [13]:
import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    print(tf.eye(20000,10000))

    # Printing how long it took with CPU
    end = time.time() - start
    print("CPU: ", end)

# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU

    print(tf.eye(20000,10000))

    # Printing how long it took with CPU
    end = time.time() - start
    print("GPU: ",end)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(20000, 10000), dtype=float32)
CPU:  0.34366941452026367
tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(20000, 10000), dtype=float32)
GPU:  0.8480832576751709


# Operações Comuns com Tensorflow

* Montando tensores com tf.constant e tf.Variable
* Concatenação de dois tensores com tf.concat
* Montando tensores com tf.zeros ou tf.ones
* Remodelando  com tf.reshape
* Cast de tensores para outros tipos de dados com tf.cast


## Montando tensores

In [14]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

## Concatenção

In [15]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

# Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(
    AB_concatenated.numpy()
))

# Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{0}').format(
    AB_concatenated.numpy()
))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]

Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


## Criando tensores com apenas zeros ou uns

In [16]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape

In [17]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                             shape = [1, 8])

print(('Tensor BEFORE reshape:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor AFTER reshape:\n{0}').format(
    reshaped_tensor.numpy()
))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


## Cast

In [18]:
# Making a tensor
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

print(('Tensor with floats:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(
    tensor_as_int.numpy()
))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


## Algebra Linear

* Transpor o tensor com tf.transpose
* Multiplicação de matrizes com tf.matmul
* Multiplicação por elementos com tf.multiply
* Matriz identidade com tf.eye
* Determinante com tf.linalg.det
* Produto de ponto com tf.tensordot

## Transpose

In [19]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
    A
))

The transposed matrix A:
[[3 1]
 [7 9]]


## Multiplicação de Matrizes

In [20]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Some vector v
v = tf.constant([[5, 2],
                 [2, 3]])

# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

v = tf.matmul(Av, A)
print(v)

Matrix Multiplication of A and v results in a new Tensor:
[[29 27]
 [23 29]]
tf.Tensor(
[[114 446]
 [ 98 422]], shape=(2, 2), dtype=int32)


## Multiplicação de matrix por um elemento

In [21]:
# Element-wise multiplication
v = tf.constant([3])
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Element-wise multiplication of A and v results in a new Tensor:
[[ 9 21]
 [ 3 27]]


## Calculando matriz Identidade

In [22]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(
    rows, columns
))

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(
    A_identity.numpy()
))

Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


## Determinante

In [23]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(
    det_A
))

The determinant of A:
20.000001907348633


## Dot Product

In [25]:
# Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

#A = tf.constant([[32, 83],
#                 [17, 23]])


# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                 [91, 10, 95],
                 [37, 13, 45]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(
    dot_AB
))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
#AB = tf.matmul(A, B)

#print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(
#AB
#))

Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


# Exemplos de aplicações

# Diferença de números primos

We have a very special vector, where the `i`th element is equal to the absolute difference of `i`th prime number squared and `i+1`th prime number squared. For example,  the 1st element in this vector is $|2^2 - 3^2| = 5$. Create this vector using TensorFlow operations.

Um vetor tem o elemento i (i=1) igual à diferença absoluta do i número primo ao quadrado e i + 1 número primo ao quadrado. 
Por exemplo, o primeiro elemento neste vetor é $|2^2 - 3^2| = 5$
Crie esse vetor usando operações do TensorFlow.

In [ ]:
prime_numbers = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23])

shifted_prime_numbers = tf.concat([prime_numbers[1:], [29]], axis=0)

diffs = tf.abs(tf.square(prime_numbers) - tf.square(shifted_prime_numbers))

assert tf.math.reduce_all(diffs == tf.constant([5,  16,  24,  72,  48, 120,  72, 168, 312])).numpy()
print("Passed")

### Exercise #3: Normalized Euclidean Distance 

Suppose that we have two sets of d-dimensional vectors. Our goal is to calculate the normalized euclidean distance between each vector of these two sets. That is, given $S_1 \in R^{m \times d}$ and $S_1 \in R^{n \times d}$, we want to calculate the $X \in R^{m \times n}$. Euclidean distance between two vector V and W is calculated as follows:

$$
dist = \sqrt{(V_1 - W_1)^2 + ... +\:(W_d - W_d)^2}
$$

Please note that we want to calculate the normalized distance, which is within the [0, 1] range. Therefore, you should normalize the similarity scores across each row.

In [2]:
def euclidean_norm_distance(v, w):
  # v = (3, 5)
  # w = (2, 5)
  n = tf.shape(v)[0] # 3
  m = tf.shape(w)[0] # 2

  v = tf.tile(tf.expand_dims(v, 1), [1, m, 1]) # (n, m, d)
  w = tf.tile(tf.expand_dims(w, 1), [1, n, 1]) # (m, n, d)
  w = tf.transpose(w, [1, 0, 2]) # (n, m, d)

  distances = (v - w) # (n, m, d)
  distances = distances ** 2 # (n, m, d)
  distances = tf.math.reduce_sum(distances, axis=2) # (n, m)
  distances = tf.math.sqrt(distances) # (n, m)

  sum_distances = tf.reshape(tf.math.reduce_sum(distances, axis=1), [-1, 1]) # (n, 1)
  distances = distances / sum_distances # (n, m)

  return distances

In [3]:
t1 = tf.constant([[-1.8897635 ,  0.7396171 ,  0.4683413 ,  2.35642   , -0.8153529 ],
       [ 1.3100415 ,  0.6090922 ,  0.70573515,  0.07053893, -0.20450763],
       [-0.14293706, -0.94566655,  0.41517866,  0.9539284 , -0.9522885 ]])
t2 = tf.constant([[ 0.4980808 ,  0.12677321, -1.6533084 ,  1.2168828 ,  0.351612  ],
       [-0.35999015, -1.013327  , -1.4144444 ,  0.83520454,  1.4889846 ]])

answer = tf.constant([[0.4718873, 0.5281127 ],
 [0.43739235, 0.5626077 ],
 [0.47395885, 0.52604115]])

assert np.allclose(euclidean_norm_distance(t1, t2).numpy(), answer)
print("Passed!")

NameError: name 'tf' is not defined